import type { NextPage } from "next";
import { GetServerSideProps } from 'next';
import Head from "next/head";
import Hero from "../components/hero";
import Drops from "../components/drops";
import Faq from "../components/faq";
import WhatIsItAbout from "../components/whats-about";
import Header from "../components/header";
import Footer from "../components/footer"


const Home: NextPage = ({ nfts }: any) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&display=swap"
          rel="stylesheet"
        />
      </Head>
      <div className="headerContainer absolute w-[100%]">
        <Header />
      </div>
      <Hero />
      <WhatIsItAbout />
      <Drops nfts={nfts}/>
      <Faq />
      <Footer />
    </div>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async () => {
  const res = await fetch(`https://backstage-hacktoberfest-service.vercel.app/api/nfts`);
  const nfts_json = await res.json();
  const nfts = getRandomNFTs(nfts_json.nfts, 6);
  return {
    props: {
      nfts
    }
  };
}

// function to get a random item from an array
const getRandomNFTs = (nfts, count) => {
  const rNFTs = [];
  for (let i = 0; i < count; i++) {
    // get random index value
    const randomIndex = Math.floor(Math.random() * nfts.length);
  
    // get random item
    const item = nfts[randomIndex];
    rNFTs.push(item);
  }
  return rNFTs;
}
